"""Archive and rooftop transactions, staging, recovery and accessible inputs."""
def run_setpiece_regressions(browser):
    p=newpage(browser);load(p,3)
    start=state(p)['f'].get('ladderX',769)
    a=p.locator('[data-hotspot="ladder"]').bounding_box()
    x=a['x']+a['width']/2;y=a['y']+a['height']/2
    p.mouse.move(x,y);p.mouse.down();p.mouse.move(1168,y,steps=12);p.wait_for_timeout(150)
    p.evaluate('HildaTest.flush()')
    stored=json.loads(p.evaluate('storageSnapshot()["hilda-echoes-homeward-v3"]'))
    check('Drag preview is not written to live state or autosave',state(p)['f'].get('ladderX',769)==start and stored['f'].get('ladderX',769)==start)
    p.dispatch_event('#viewport','pointercancel',{'pointerId':1});p.mouse.up();settle(p)
    check('Cancelled ladder drag restores its exact rendered origin',state(p)['f'].get('ladderX',769)==start and not ui(p)['working'])
    act(p,'ladder');act(p,'ladder');act(p,'ladderBrake')
    before=state(p)['f']['ladderX'];drag_object(p,'ladder',target=(700,643))
    check('Locked ladder cannot be moved with a scene drag',state(p)['f']['ladderX']==before)
    p.locator('[data-hotspot="book"]').click();p.wait_for_function('HildaTest.ui().working');p.wait_for_function('HildaTest.ui().performance.progress>.46')
    transform=p.locator('#heroPosition').get_attribute('transform')
    foot=float(transform.split()[1].rstrip(')'))
    check('Climbing actor reaches the upper shelf while saved feet remain grounded',foot<560 and ui(p)['hero']['y']==819 and not flags(p,'planTaken'))
    p.screenshot(path=str(ROOT/'previews/v32-archive-climb.png'))
    p.locator('#menuBtn').click();progress=ui(p)['performance']['progress'];paused=p.locator('#heroPosition').get_attribute('transform');p.wait_for_timeout(350)
    check('Climb pauses mid-rung without drifting',ui(p)['performance']['progress']==progress and p.locator('#heroPosition').get_attribute('transform')==paused)
    p.evaluate('HildaTest.flush()');storage=p.evaluate('storageSnapshot()')
    q=newpage(browser,storage=storage);q.locator('#continueBtn').click();settle(q)
    check('Reload during climb keeps ladder locked and book available',flags(q,'ladderBrake') and not flags(q,'planTaken') and 'plan' not in state(q)['inventory'])
    act(q,'book');check('Interrupted climb can be retried without duplicate rewards',state(q)['inventory'].count('plan')==1)
    q.close();p.locator('#resumePlay').click();settle(p)
    check('Completed climb returns the visible actor to the floor',p.locator('#heroPosition').get_attribute('transform').endswith('819.0)'))
    load(p,9);choose(p,'line');p.locator('[data-hotspot="anchor"]').click();p.wait_for_function('HildaTest.ui().working')
    check('Anchor preparation retains rope until the knot is completed','line' in state(p)['inventory'] and not flags(p,'roofAnchor'))
    settle(p);p.locator('[data-hotspot="david"]').click();p.wait_for_function('HildaTest.ui().working');p.wait_for_function('HildaTest.ui().performance.progress>.55')
    dx=float(p.locator('#roofDavid').get_attribute('transform').split('(')[1].split()[0])
    check('David moves visibly along the secured rescue line before rescue commits',466<dx<670 and not flags(p,'davidSafe'))
    p.screenshot(path=str(ROOT/'previews/v32-roof-rescue.png'));settle(p);act(p,'david')
    choose(p,'pole');p.locator('[data-hotspot="frida"]').click();p.wait_for_function('HildaTest.ui().working');p.wait_for_function('HildaTest.ui().performance.progress>.5')
    check('Beam lifts visibly while David braces and Frida moves free',flags(p,'roofBrace') and p.locator('#roofBeam').get_attribute('transform').startswith('rotate(24') and not flags(p,'fridaSafe'))
    p.screenshot(path=str(ROOT/'previews/v32-roof-lever.png'));settle(p)
    done=state(p);p.evaluate('HildaTest.resetRoof()');settle(p)
    check('Retreat retains rescued companions, brace and reusable pole',flags(p,'davidSafe','fridaSafe','roofBrace') and 'pole' in state(p)['inventory'] and state(p)['failures']==done['failures']+1)
    a=p.locator('[data-hotspot="beacon"]').bounding_box();x=a['x']+a['width']/2;y=a['y']+a['height']/2
    old=state(p)['beaconAngle'];p.mouse.move(x,y);p.mouse.down();p.mouse.move(x-90,y-150,steps=12);p.evaluate('HildaTest.flush()')
    check('Beacon preview does not accidentally commit or summon rescue',state(p)['beaconAngle']==old and not flags(p,'beacon'))
    p.keyboard.press('Escape');p.mouse.up();check('Opening menu cancels the pending pointer transaction',ui(p)['modal'] and state(p)['beaconAngle']==old)
    p.locator('#resumePlay').click();settle(p)
    for _ in range(3):act(p,'beacon',keyboard=True)
    act(p,'twig',keyboard=True);shot(p,'v32-roof-ready')
    check('Keyboard can complete the revised signal and pet rescue',flags(p,'beacon','twigSafe'))
    overlaps=p.evaluate("""()=>HildaTest.hotspots().filter(h=>{const r=document.querySelector('[data-hotspot="'+h.id+'"]').getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('[data-hotspot]')?.dataset.hotspot!==h.id}).map(h=>h.id)""")
    check('Rescued companions and low wheel retain unobstructed hotspot centres',not overlaps)
    p.locator('[data-hotspot="board"]').click()
    until=time.monotonic()+20
    while not ui(p)['working'] and time.monotonic()<until:
        if ui(p)['dialogue']:p.keyboard.press('Space')
        p.wait_for_timeout(65)
    p.wait_for_function('HildaTest.ui().performance?.progress>.81')
    aboard={name:p.locator('#'+name).get_attribute('transform') for name in ['heroPosition','roofDavid','roofFrida','twigPosition']}
    check('All four visible companions board the same Woff before departure',all(float(v.split()[1].split(')')[0])<620 for v in aboard.values()) and not flags(p,'roofDone'))
    p.locator('#menuBtn').click();before=ui(p)['performance']['progress'];p.wait_for_timeout(150)
    check('Group departure can pause without committing the next chapter',ui(p)['performance']['progress']==before and state(p)['scene']==9)
    p.screenshot(path=str(ROOT/'previews/v32-boarding-paused.png'))
    p.locator('#resumePlay').click();settle(p)
    check('Completed group departure reaches the dawn ridge exactly once',state(p)['scene']==10 and flags(p,'roofDone'))
    p.close()
    m=newpage(browser,844,390,True);load(m,3)
    act(m,'ladder',touch=True);act(m,'ladder',touch=True);act(m,'ladderBrake',touch=True)
    m.locator('#menuBtn').tap();m.locator('#motionSetting').tap();m.locator('#resumePlay').tap();act(m,'book',touch=True)
    check('Touch and reduced-motion mode complete the revised archive',flags(m,'planTaken','ladderBrake') and state(m)['settings']['reduced'])
    ids=m.evaluate('()=>Array.from(document.querySelectorAll("#world [id]")).map(n=>n.id)')
    check('New setpiece art and actor layers retain unique SVG identifiers',len(ids)==len(set(ids)))
    shot(m,'v32-mobile-archive');m.close()
