Homeward.define("scene/9/logic", ["story/helpers", "content/catalog"], ({checkBeacon,H,I,exit,f,say,one,wrong,set,need,advance,book,pipeCheck,balance,lightTrail}, {items,notes}) => {

return {
name:'风暴之上的约定',english:'NO ONE LEFT BEHIND',actLabel:'第四幕 · 别松开我的手',mood:'钟楼屋顶 / 谁都不能被留在风里',start:315,ground:x=>x<490?767:x<750?746:773,
intro:[['大卫','我在这里！瓦片掉了，我过不去！'],['芙丽达','我的背包被横梁压住了。希尔达，先把绳子固定！'],['希尔达','听我的。我们一个接一个来，谁都不会被留下。']],
hotspots:s=>[H('anchor','把救援绳固定到近处铁环',426,652,83,115,{walkX:415}),H('david','把大卫拉回安全屋面',s.f.davidSafe?824:670,s.f.davidSafe?644:629,109,204,{walkX:s.f.davidSafe?800:453}),H('frida','撬开压住芙丽达的横梁',1045,662,178,204,{walkX:960}),H('beacon','转动信标，照向山脊星标',1292,492,176,181,{drag:'beacon',walkX:1211}),...(!s.f.twigSafe?[H('twig','带上枝枝',929,686,118,83,{walkX:876})]:[]),exit('board','一起登上沃夫的背',1395,644,{walkX:1326}),H('star','观察远处山脊的星标',1044,176,55,59,{walkX:1128})],
act(g,id,item){if(id==='anchor'){if(f(g,'roofAnchor'))return g.toast('绳头固定好了。现在把另一端抛给大卫。');if(!need(g,'line',item,'使用升降站带来的救援绳，先牢牢固定近处这一端。'))return;g.consume('line');set(g,'roofAnchor');book(g,'rescue');g.sound('rope');g.toast('救援绳牢牢固定。点击大卫，把另一端抛过去。');}else if(id==='david'){if(f(g,'davidSafe'))return one(g,'大卫','我会照看枝枝。先去帮芙丽达！');if(!f(g,'roofAnchor'))return one(g,'大卫','别直接跳过来！先固定绳子！');g.work(1600,'抓紧绳子，把大卫拉回安全处',()=>{set(g,'davidSafe');g.sound('rope');g.toast('大卫脱险了。绳索也让大家能够跨过断口。');});}else if(id==='frida'){if(f(g,'fridaSafe'))return one(g,'芙丽达','沃夫会循着亮光过来。转动屋顶的信标，朝向左上方的山脊星标。');if(!f(g,'davidSafe'))return one(g,'希尔达','我还不能越过屋顶断口。先用绳子救大卫。');if(!need(g,'pole',item,'梁下有一条缝。用带回来的长柄检修挑杆借力。大卫扶稳支点，芙丽达才能拉出背包。'))return;g.work(1000,'和大卫一起稳住支点，用长挑杆抬起横梁',()=>{set(g,'fridaSafe');g.toast('芙丽达脱险。检修挑杆已取回。现在需要一条离开屋顶的路。');});}else if(id==='beacon'){if(!f(g,'fridaSafe'))return one(g,'希尔达','先把朋友从危险的地方救出来。');if(f(g,'beacon'))return g.toast('信标已经指向山脊。沃夫来了！');g.s.beaconAngle-=21;if(g.s.beaconAngle<-178)g.s.beaconAngle=-45;g.commit();checkBeacon(g);}else if(id==='twig'){if(!f(g,'davidSafe'))return one(g,'希尔达','枝枝，待在原地。我先把绳桥拉好。');set(g,'twigSafe');g.sound('warm');g.toast('枝枝跳到了希尔达身边。一个都不能少。');}else if(id==='board'){if(!f(g,'beacon'))return one(g,'芙丽达','先用信标招来沃夫。照向左上方远处的星标。');if(!f(g,'twigSafe'))return one(g,'希尔达','等一下，枝枝还在屋面上！');set(g,'roofDone');say(g,[['大卫','我抓住芙丽达了！'],['芙丽达','枝枝在这里。希尔达，把手给我！'],['希尔达','大家都在。现在，带我们去山脊！']],()=>g.go(10));}else if(id==='star')g.toast('远处的星标在信标的左上方。让转轮指针和光线朝向它。');else wrong(g);},
drag(g,id,p){if(id==='beacon'&&f(g,'fridaSafe')&&!f(g,'beacon')){g.s.beaconAngle=Math.atan2(p.y-492,p.x-1292)*180/Math.PI;g.commit();checkBeacon(g);return true;}return false;},
objective:s=>!s.f.roofAnchor?'用救援绳固定近处铁环。':!s.f.davidSafe?'把大卫从断口另一侧拉回来。':!s.f.fridaSafe?'用检修挑杆撬开压住芙丽达的横梁。':!s.f.beacon?'把信标照向左上方的山脊星标。':!s.f.twigSafe?'带上枝枝，谁也不落下。':'和所有同伴一起登上沃夫。',
hints:s=>['先救朋友，再寻找离开屋顶的路。打开手记和菜单时风暴会暂停。','救援绳固定近处铁环后才能拉大卫；长柄挑杆能撬横梁；最后调整信标方向。','依次：绳子用于铁环 → 点大卫 → 检修挑杆用于芙丽达 → 点信标三次（或向左上拖转）→ 点枝枝 → 点沃夫。可在设置开启舒缓模式。']};
});
