Homeward.define("scene/2/logic", ["story/helpers", "content/catalog"], ({checkBeacon,H,I,exit,f,say,one,wrong,set,need,advance,book,pipeCheck,balance,lightTrail}, {items,notes}) => {

return {
name:'溪水逆流的森林',english:'THE STREAM RUNS BACKWARDS',actLabel:'第一幕 · 跟着回声走',mood:'最后一线暮色 / 水声似乎走错了方向',start:248,ground:(x,s)=>{if(s?.f?.bridge&&x>=500&&x<=1090){if(x<550)return 771+(x-500)/50*(706-771);if(x<=1040)return 706+Math.sin((x-550)/490*Math.PI)*20-(x-550)*0.035;return 689+(x-1040)/50*(768-689);}return x<550?771:x>1090?768:771+Math.sin((x-550)/540*Math.PI)*22;},
intro:[['希尔达','钟声之后，水竟然往山上流了。'],['大卫','桥也断了。我们现在回去，算不算观察得很仔细？'],['希尔达','还差一点。比如，桥那边为什么有精灵的路标。']],
hotspots:s=>[...(!s.f.ropeTaken?[I('rope','收起旧绳圈',331,725,72,65)]:[]),...(!s.f.hookTaken?[H('hook',s.f.branchBent?'取下压低树枝上的铁钩':'观察挂在高处的铁钩',541,s.f.branchBent?642:496,75,95,{walkX:495})]:[]),H('anchor','对岸的铁环',1095,556,85,122,{walkX:s.f.bridge?1042:516}),H('winch','转动桥边的绞盘',481,651,107,116,{walkX:460}),H('stream','观察逆流的溪水',790,776,193,82,{walkX:s.f.bridge?774:492}),exit('next','沿着根下的路标前进',1351,699,{walkX:1352}),exit('back','回北门',95,738,{walkX:157})],
act(g,id,item){if(id==='rope'){set(g,'ropeTaken');g.take('rope');}else if(id==='hook'){if(f(g,'hookTaken'))return;if(!f(g,'branchBent')){if(item==='rope'){g.work(900,'抛出旧绳圈套住野藤，用力拉低树枝...',()=>{set(g,'branchBent');g.sound('rope');say(g,[['希尔达','套住了！大卫，帮我拽住绳子！'],['大卫','我拉着呢！树枝弹力好大，你快去摘钩子！']]);});}else{say(g,[['希尔达','太高了！铁钩缠在悬空的野藤上……树枝很有弹性，要是有绳子把它拽下来就好了。'],['大卫','地上的旧绳圈……说不定能当套索抛上去套住藤蔓？']]);}}else{set(g,'hookTaken');set(g,'branchBent',false);g.sound('wood');g.take('hook');g.toast('铁钩取下了！树枝弹回原位，旧绳圈也收回背包。');}}else if(id==='anchor'){if(f(g,'grappleSet'))return g.toast('绳索已经牢牢挂住对岸了。');if(!need(g,'grapple',item,'太远了。绳子需要一只能够抓住铁环的钩。'))return;g.work(800,'对准对岸铁环，用力甩出飞钩...',()=>{g.consume('grapple');set(g,'grappleSet');g.effect('rope');g.toast('带钩绳索牢牢扣住了对岸。现在可以转动绞盘。');});}else if(id==='winch'){if(f(g,'bridge'))return g.toast('桥板已经固定好了。');if(!f(g,'grappleSet'))return one(g,'希尔达','只转绞盘，会把断桥拖进水里。先固定对岸。');g.work(1250,'把桥板慢慢拉回水面',()=>{set(g,'bridge');g.sound('wood');say(g,[['大卫','咔哒一声咬住了！它平平整整架在两岸石墩上了！'],['希尔达','好消息：桥面很结实。走吧，我们一起踩着桥过去。']]);});}else if(id==='stream'){book(g,'water');one(g,'希尔达','不是风。钟声每响一次，水就被抽向山里一次。');}else if(id==='next'){if(f(g,'bridge'))book(g,'water');advance(g,f(g,'bridge'),3,'先把桥固定好。我们必须一起过去。');}else if(id==='back')g.go(1);else wrong(g);},
objective:s=>!s.f.hookTaken?(s.f.branchBent?'取下压低树枝上的铁钩。':'想办法拿到高处的铁钩。'):!s.f.grappleSet?'把绳索和铁钩组合成带钩绳索。':!s.f.bridge?'用绞盘拉起断桥。':'沿路标寻找精灵档案室。',
hints:s=>[!s.f.hookTaken?(s.f.branchBent?'点击被压低树枝上的铁钩把它取下。':'铁钩挂在树上太高。先捡起地上的旧绳圈，在背包选中绳圈，再点高处的铁钩套住野藤拽下树枝。'):!s.f.grappleSet?'打开背包，先选旧绳圈，再点铁钩，组合成带钩绳索。':'把带钩绳索拖到右岸铁环（或先选中再点铁环）。然后转动左岸绞盘拉起桥板。']};
});
