Homeward.define("scene/8/logic", ["story/helpers", "content/catalog"], ({checkBeacon,H,I,exit,f,say,one,wrong,set,need,advance,book,pipeCheck,balance,lightTrail}, {items,notes}) => {

return {
name:'水钟的机械心脏',english:'THE HEART OF THE WATER CLOCK',actLabel:'第四幕 · 别松开我的手',mood:'先让水找到出口，再让钟安静',start:411,ground:x=>833,chapter:['ACT IV','别松开我的手','有些机关，必须由朋友一起转动。'],
intro:[['大卫','终于到了。把钟停下来，我们就能走了吧？'],['芙丽达','别急。图纸上有一句被折住了：停钟，也会锁住泄洪闸。'],['希尔达','所以我们不是来让它停止。是来教它重新好好工作。']],
hotspots:s=>[H('plan','再看一眼维护图',303,677,170,133,{walkX:351}),H('bypass','打开泄压旁路',440,556,122,173),...(!s.f.feltTaken?[I('felt','拾起羊毛毡',553,768,99,75)]:[]),H('clapper','给钟舌加上软垫',838,457,171,117,{walkX:789}),H('frida','请芙丽达稳住旁路拉杆',1272,677,96,209,{walkX:1182}),H('david','请大卫稳住制动杆',1070,683,107,204,{walkX:994}),H('drive','摇动排洪飞轮',662,566,181,184,{walkX:668}),exit('next','爬上屋顶',1481,633,{walkX:1440})],
act(g,id,item){if(id==='plan'){book(g,'bypass');one(g,'芙丽达','先旁路、再缓冲、两人稳住制动，最后转飞轮。顺序错了，水会替我们做决定。');}else if(id==='bypass'){if(f(g,'bypass'))return g.toast('旁路已经全开，压力稳定了。');if(!f(g,'bypassMounted')){if(!need(g,'crank',item,'阀轴锈得拧不动。借用北门带来的曲柄。'))return;set(g,'bypassMounted');g.toast('曲柄装好了。再转两圈，把旁路完全打开。');}else{set(g,'bypassTurns',(g.s.f.bypassTurns||0)+1);g.sound('metal');if(g.s.f.bypassTurns>=2){set(g,'bypass');book(g,'bypass');g.toast('旁路打开，洪水终于有了第二个出口。曲柄已取回。');}else g.toast('压力在下降。再转一圈。');}}else if(id==='felt'){set(g,'feltTaken');g.take('felt');}else if(id==='clapper'){if(f(g,'damped'))return g.toast('钟舌已经包上羊毛毡。钟声不再刺耳。');if(!need(g,'felt',item,'直接敲击的钟舌很刺耳。地上的羊毛毡能缓冲撞击。'))return;if(!f(g,'bypass')){g.effect('shake');return say(g,[['大卫','压力表！它一下就冲上去了！'],['芙丽达','快松开。羊毛毡没丢。先打开左边的泄压旁路。']]);}g.work(900,'踩着石座台阶，将羊毛毡严严实实垫进钟舌与撞锤之间...',()=>{g.consume('felt');set(g,'damped');g.sound('warm');one(g,'希尔达','这次，钟可以说话，而不用大喊大叫了。');});}else if(id==='frida'){if(!f(g,'bypass')||!f(g,'damped'))return one(g,'芙丽达','先准备旁路和钟舌。我不能一边压着拉杆，一边帮你修它们。');set(g,'fridaHold');one(g,'芙丽达','我稳住旁路。你去转飞轮，别担心这边。');}else if(id==='david'){if(!f(g,'bypass')||!f(g,'damped'))return one(g,'大卫','先把水和钟处理好。我正在练习不害怕。');set(g,'davidHold');one(g,'大卫','我还是很害怕。但我会握住它。');}else if(id==='drive'){if(f(g,'heart'))return g.toast('排洪机构已经重新运转。');if(!f(g,'fridaHold')||!f(g,'davidHold'))return one(g,'希尔达','飞轮一转，拉杆就会弹回去。要请芙丽达和大卫一起帮忙。');if(!need(g,'fork',item,'飞轮的共鸣锁缺少音叉。小巨魔给的那支，正好能嵌进去。'))return;g.consume('fork');g.work(1800,'三个人一起，让老水钟重新运转',()=>{set(g,'heart');g.effect('water');g.sound('warm');say(g,[['希尔达','它听懂了！水正在流回山谷！'],['大卫','我们做到了？我们真的……'],['芙丽达','退潮的水撞上塔基了。楼梯下面也全是水。'],['希尔达','去屋顶！拉住彼此，别回头！']]);});}else if(id==='next')advance(g,f(g,'heart'),9,'离开前必须把泄洪机构修好。阿尔弗和孩子还在山上等我们。');else wrong(g);},
objective:s=>!s.f.bypass?'用曲柄打开泄压旁路。':!s.f.damped?'用羊毛毡给钟舌缓冲。':!s.f.fridaHold||!s.f.davidHold?'让两位同伴分别稳住机构。':!s.f.heart?'把回声音叉嵌入飞轮，重新排洪。':'水正在涌来，爬上屋顶！',
hints:s=>['直接停钟会锁住泄洪。先看左下的维护图。','曲柄用于左边的阀，羊毛毡用于钟舌。同伴可以稳住拉杆与制动。','装上曲柄后再转旁路两次，垫上羊毛毡，分别点芙丽达和大卫；最后选音叉并点中央飞轮。']};
});
