Homeward.define("scene/6/logic", ["story/helpers", "content/catalog"], ({checkBeacon,H,I,exit,f,say,one,wrong,set,need,advance,book,pipeCheck,balance,lightTrail}, {items,notes}) => {

return {
name:'巨人掌心的避风处',english:'THE CHILD UNDER THE MOUNTAIN',actLabel:'第三幕 · 听懂它的害怕',mood:'夜已深 / 那座山，似乎也在呼吸',start:424,ground:x=>790,chapter:['ACT III','听懂它的害怕','不是每一个庞大的影子，都在挡住你的路。'],
intro:[['大卫','希尔达……后面那座山，刚刚眨了眼。'],['希尔达','它在替这个孩子挡风。它不是要伤害我们。'],['芙丽达','小一点声。提灯也太亮了。']],
hotspots:s=>[H('child','靠近小巨魔',956,670,152,183,{walkX:873}),H('holder','把柔和的灯放在石座上',782,672,71,90,{walkX:801}),H('song','看看石壁上的歌',610,375,214,187,{walkX:613}),...[0,1,2].map(i=>H('tone'+i,['溪流石','松针石','月亮石'][i],468+i*118,685-i%2*22,100,139,{walkX:560})),H('frida','问问芙丽达',1149,690,99,178),exit('next','穿过山的怀抱',1240,654,{walkX:1285})],
act(g,id,item){if(id==='child'){if(f(g,'calm'))return one(g,'希尔达','阿尔弗会陪它沿着避洪小径走。我们把钟声修好，再到山脊会合。');if(!f(g,'shadePlaced')){g.effect('soft');return one(g,'芙丽达','它把眼睛捂住了。用围巾遮住提灯，让光柔和一点。');}one(g,'希尔达','它在敲石头，像是在等一段熟悉的歌。石壁上也许有线索。');}else if(id==='holder'){if(f(g,'shadePlaced'))return g.toast('暖光不再刺眼，孩子慢慢放松了。');if(!need(g,'shade',item,'它需要柔和的光。把妈妈的围巾和提灯组合起来。'))return;g.consume('shade');g.take('lamp',false);set(g,'shadePlaced');g.sound('warm');say(g,[['希尔达','这样好多了，对不对？我们不急。'],['芙丽达','围巾留在石灯上就好。我们仍可以带走提灯。']]);}else if(id==='song'){book(g,'song');g.playSequence([0,1,0,2]);}else if(id.startsWith('tone')){if(f(g,'calm'))return g.pulse('tone'+id.slice(-1),Number(id.slice(-1)));if(!f(g,'shadePlaced'))return one(g,'希尔达','先让它安心。害怕的时候，谁都听不进去歌。');let v=Number(id.slice(-1));g.pulse('tone'+v,v);g.s.melody.push(v);if(g.s.melody.length===4){if(g.s.melody.every((k,i)=>k===[0,1,0,2][i])){set(g,'calm');g.take('fork',false);book(g,'child');say(g,[['希尔达','它把一支音叉放到了我手里……钟楼缺的，是不是这个？'],['阿尔弗','原来它只是想把音叉送回去。钟声太响，它的妈妈不敢接近城墙。'],['芙丽达','我们去修好钟。阿尔弗，你带它走山背后的避洪小径。'],['希尔达','在山脊的路灯下会合。一个都不能少。']]);}else g.toast('最后一块石头没有回应。再听一遍石壁上的歌。');g.s.melody=[];}g.commit();}else if(id==='frida')one(g,'芙丽达',f(g,'calm')?'我和大卫跟你去钟楼。阿尔弗知道另一条通往山脊的路。':'先遮住刺眼的灯，再用石壁记着的顺序敲石头。');else if(id==='next')advance(g,f(g,'calm'),7,'先帮这个孩子平静下来。它已经一个人等得够久了。');else wrong(g);},
objective:s=>!s.f.shadePlaced?'用柔和的灯光安抚小巨魔。':!s.f.calm?'听石壁的歌，敲响三块回声石。':'让阿尔弗照看孩子，和同伴去钟楼。',
hints:s=>['孩子怕强光，也怕突如其来的声音。','把围巾和提灯组合，放到石座上。再点击高处的石壁，观察回声石亮起的顺序。','组合遮光提灯并使用后，依次点击：溪流、松针、溪流、月亮。']};
});
